{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vph9VucJEHVI",
        "outputId": "86f7fe1a-6c32-4fe3-b69c-9bd060effa03"
      },
      "outputs": [],
      "source": [
        "# !unzip /content/DiffMorph-master.zip\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "ERROR: unknown command \"instal\" - maybe you meant \"install\"\n"
          ]
        }
      ],
      "source": [
        "!pip instal"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "XnZLc2KKEsFZ",
        "outputId": "7e8b5741-bcd1-4696-84ec-c839f9513456"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: numpy==1.21.6 in ./JAGGU/lib/python3.9/site-packages (from -r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 1)) (1.21.6)\n",
            "Requirement already satisfied: tensorflow==2.9.1 in ./JAGGU/lib/python3.9/site-packages (from -r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.9.1)\n",
            "Requirement already satisfied: tensorflow-addons==0.17.1 in ./JAGGU/lib/python3.9/site-packages (from -r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 3)) (0.17.1)\n",
            "Requirement already satisfied: opencv-python==4.6.0.66 in ./JAGGU/lib/python3.9/site-packages (from -r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 4)) (4.6.0.66)\n",
            "Requirement already satisfied: tqdm==4.64.0 in ./JAGGU/lib/python3.9/site-packages (from -r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 5)) (4.64.0)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (4.4.0)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.14.1)\n",
            "Requirement already satisfied: keras-preprocessing>=1.1.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.1.2)\n",
            "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.4.0)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.2.0)\n",
            "Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.9.0)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.28.0)\n",
            "Requirement already satisfied: h5py>=2.9.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.7.0)\n",
            "Requirement already satisfied: tensorboard<2.10,>=2.9 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.9.1)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.1.1)\n",
            "Requirement already satisfied: six>=1.12.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.16.0)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.3.0)\n",
            "Requirement already satisfied: flatbuffers<2,>=1.12 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.12)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.50.0)\n",
            "Requirement already satisfied: packaging in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (21.3)\n",
            "Requirement already satisfied: libclang>=13.0.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (14.0.6)\n",
            "Requirement already satisfied: absl-py>=1.0.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.3.0)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.6.3)\n",
            "Requirement already satisfied: protobuf<3.20,>=3.9.2 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.19.6)\n",
            "Requirement already satisfied: setuptools in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (58.1.0)\n",
            "Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.9.0)\n",
            "Requirement already satisfied: typeguard>=2.7 in ./JAGGU/lib/python3.9/site-packages (from tensorflow-addons==0.17.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 3)) (2.13.3)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in ./JAGGU/lib/python3.9/site-packages (from astunparse>=1.6.0->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.38.4)\n",
            "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.4.6)\n",
            "Requirement already satisfied: markdown>=2.6.8 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.4.1)\n",
            "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.8.1)\n",
            "Requirement already satisfied: google-auth<3,>=1.6.3 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.14.1)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.2.2)\n",
            "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.6.1)\n",
            "Requirement already satisfied: requests<3,>=2.21.0 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.28.1)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./JAGGU/lib/python3.9/site-packages (from packaging->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.0.9)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./JAGGU/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.2.8)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./JAGGU/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (5.2.0)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in ./JAGGU/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (4.9)\n",
            "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./JAGGU/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.3.1)\n",
            "Requirement already satisfied: importlib-metadata>=4.4 in ./JAGGU/lib/python3.9/site-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (5.1.0)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (1.26.13)\n",
            "Requirement already satisfied: idna<4,>=2.5 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.4)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2022.9.24)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.1.1)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in ./JAGGU/lib/python3.9/site-packages (from werkzeug>=1.0.1->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (2.1.1)\n",
            "Requirement already satisfied: zipp>=0.5 in ./JAGGU/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.11.0)\n",
            "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./JAGGU/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (0.4.8)\n",
            "Requirement already satisfied: oauthlib>=3.0.0 in ./JAGGU/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow==2.9.1->-r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt (line 2)) (3.2.2)\n",
            "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\n",
            "You should consider upgrading via the '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "! pip install -r /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/requirements.txt"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "JuPXeN8sEyb6",
        "outputId": "3650a5f6-5cad-4835-f5de-032862961c61"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Collecting pymorphy2\n",
            "  Using cached pymorphy2-0.9.1-py3-none-any.whl (55 kB)\n",
            "Collecting docopt>=0.6\n",
            "  Using cached docopt-0.6.2.tar.gz (25 kB)\n",
            "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
            "\u001b[?25hCollecting pymorphy2-dicts-ru<3.0,>=2.4\n",
            "  Using cached pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl (8.2 MB)\n",
            "Collecting dawg-python>=0.7.1\n",
            "  Using cached DAWG_Python-0.7.2-py2.py3-none-any.whl (11 kB)\n",
            "Building wheels for collected packages: docopt\n",
            "  Building wheel for docopt (setup.py) ... \u001b[?25ldone\n",
            "\u001b[?25h  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13723 sha256=f8f89177c2a0851a568932dbe7dcdcb02b5e043781d48a71a982d943daadbf2c\n",
            "  Stored in directory: /home/hpc-lavasa/.cache/pip/wheels/70/4a/46/1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b\n",
            "Successfully built docopt\n",
            "Installing collected packages: pymorphy2-dicts-ru, docopt, dawg-python, pymorphy2\n",
            "Successfully installed dawg-python-0.7.2 docopt-0.6.2 pymorphy2-0.9.1 pymorphy2-dicts-ru-2.4.417127.4579844\n",
            "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\n",
            "You should consider upgrading via the '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "!pip install pymorphy2"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "D4MZUIZgG3nT",
        "outputId": "e11fc272-6191-4b9f-ee44-891c06024b05"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: tensorflow-addons in ./JAGGU/lib/python3.9/site-packages (0.17.1)\n",
            "Requirement already satisfied: packaging in ./JAGGU/lib/python3.9/site-packages (from tensorflow-addons) (21.3)\n",
            "Requirement already satisfied: typeguard>=2.7 in ./JAGGU/lib/python3.9/site-packages (from tensorflow-addons) (2.13.3)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./JAGGU/lib/python3.9/site-packages (from packaging->tensorflow-addons) (3.0.9)\n",
            "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\n",
            "You should consider upgrading via the '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "!pip install tensorflow-addons"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "zXFFARFRFilc",
        "outputId": "2c38b184-7b2b-49bd-dbc2-044b0936fc1a"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "2022-11-27 02:42:49.636267: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:42:50.686152: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:50.702842: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:50.703018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:50.703381: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:42:50.704066: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:50.704197: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:50.704243: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:51.006141: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:51.006308: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:51.006365: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:42:51.006421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:42:53.003026: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:42:53.003448: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:42:53.003482: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n"
          ]
        }
      ],
      "source": [
        "!python /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py -s /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_images/0.jpg -t /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_images/1.jpg"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "WGtxflY9INM5",
        "outputId": "89165976-80c0-4ce2-e113-7b7b9c981df5"
      },
      "outputs": [],
      "source": [
        "#  !python /content/DiffMorph-master/morph.py -s /content/DiffMorph-master/images/009_02.jpg -t /content/DiffMorph-master/images/025_02.jpg"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Collecting tensorflow==2.9.1\n",
            "  Using cached tensorflow-2.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.7 MB)\n",
            "Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (2.9.0)\n",
            "Requirement already satisfied: keras-preprocessing>=1.1.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.1.2)\n",
            "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (0.4.0)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (0.28.0)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (4.4.0)\n",
            "Requirement already satisfied: setuptools in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (58.1.0)\n",
            "Requirement already satisfied: protobuf<3.20,>=3.9.2 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (3.19.6)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (2.1.1)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (3.3.0)\n",
            "Requirement already satisfied: flatbuffers<2,>=1.12 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.12)\n",
            "Requirement already satisfied: packaging in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (21.3)\n",
            "Requirement already satisfied: six>=1.12.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.16.0)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.6.3)\n",
            "Requirement already satisfied: absl-py>=1.0.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.3.0)\n",
            "Requirement already satisfied: h5py>=2.9.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (3.7.0)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.50.0)\n",
            "Collecting keras<2.10.0,>=2.9.0rc0\n",
            "  Using cached keras-2.9.0-py2.py3-none-any.whl (1.6 MB)\n",
            "Requirement already satisfied: libclang>=13.0.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (14.0.6)\n",
            "Requirement already satisfied: numpy>=1.20 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.21.6)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (1.14.1)\n",
            "Collecting tensorboard<2.10,>=2.9\n",
            "  Using cached tensorboard-2.9.1-py3-none-any.whl (5.8 MB)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in ./JAGGU/lib/python3.9/site-packages (from tensorflow==2.9.1) (0.2.0)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in ./JAGGU/lib/python3.9/site-packages (from astunparse>=1.6.0->tensorflow==2.9.1) (0.38.4)\n",
            "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1) (0.6.1)\n",
            "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1) (0.4.6)\n",
            "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1) (1.8.1)\n",
            "Requirement already satisfied: requests<3,>=2.21.0 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1) (2.28.1)\n",
            "Requirement already satisfied: markdown>=2.6.8 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1) (3.4.1)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1) (2.2.2)\n",
            "Requirement already satisfied: google-auth<3,>=1.6.3 in ./JAGGU/lib/python3.9/site-packages (from tensorboard<2.10,>=2.9->tensorflow==2.9.1) (2.14.1)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./JAGGU/lib/python3.9/site-packages (from packaging->tensorflow==2.9.1) (3.0.9)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in ./JAGGU/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (4.9)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./JAGGU/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (5.2.0)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in ./JAGGU/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (0.2.8)\n",
            "Requirement already satisfied: requests-oauthlib>=0.7.0 in ./JAGGU/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (1.3.1)\n",
            "Requirement already satisfied: importlib-metadata>=4.4 in ./JAGGU/lib/python3.9/site-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (5.1.0)\n",
            "Requirement already satisfied: idna<4,>=2.5 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (3.4)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (1.26.13)\n",
            "Requirement already satisfied: charset-normalizer<3,>=2 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (2.1.1)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in ./JAGGU/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (2022.9.24)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in ./JAGGU/lib/python3.9/site-packages (from werkzeug>=1.0.1->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (2.1.1)\n",
            "Requirement already satisfied: zipp>=0.5 in ./JAGGU/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (3.11.0)\n",
            "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./JAGGU/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (0.4.8)\n",
            "Requirement already satisfied: oauthlib>=3.0.0 in ./JAGGU/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow==2.9.1) (3.2.2)\n",
            "Installing collected packages: keras, tensorboard, tensorflow\n",
            "  Attempting uninstall: keras\n",
            "    Found existing installation: keras 2.8.0\n",
            "    Uninstalling keras-2.8.0:\n",
            "      Successfully uninstalled keras-2.8.0\n",
            "  Attempting uninstall: tensorboard\n",
            "    Found existing installation: tensorboard 2.8.0\n",
            "    Uninstalling tensorboard-2.8.0:\n",
            "      Successfully uninstalled tensorboard-2.8.0\n",
            "  Attempting uninstall: tensorflow\n",
            "    Found existing installation: tensorflow 2.8.0\n",
            "    Uninstalling tensorflow-2.8.0:\n",
            "      Successfully uninstalled tensorflow-2.8.0\n",
            "Successfully installed keras-2.9.0 tensorboard-2.9.1 tensorflow-2.9.1\n",
            "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\n",
            "You should consider upgrading via the '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
            "\u001b[0mRequirement already satisfied: tensorflow-addons==0.17.1 in ./JAGGU/lib/python3.9/site-packages (0.17.1)\n",
            "Requirement already satisfied: packaging in ./JAGGU/lib/python3.9/site-packages (from tensorflow-addons==0.17.1) (21.3)\n",
            "Requirement already satisfied: typeguard>=2.7 in ./JAGGU/lib/python3.9/site-packages (from tensorflow-addons==0.17.1) (2.13.3)\n",
            "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./JAGGU/lib/python3.9/site-packages (from packaging->tensorflow-addons==0.17.1) (3.0.9)\n",
            "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\n",
            "You should consider upgrading via the '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "! pip install tensorflow==2.9.1\n",
        "! pip install tensorflow-addons==0.17.1"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {},
      "outputs": [],
      "source": [
        "python_code_loc1 = '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py'\n",
        "image_loc1 = '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_images'\n",
        "output_loc1 = '/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/output_videos2'\n",
        "img_1 = 1\n",
        "img_2 = 2\n",
        "img_1_name = '{}.jpg'.format(img_1)\n",
        "img_2_name = '{}.jpg'.format(img_2)\n",
        "video_name = 'morphed_{}_{}.mp4'.format(img_1, img_2)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "qQIBUwlOnZA9",
        "outputId": "07dcf8e2-d91c-4d1a-a333-6fce3c5e085d"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "2022-11-27 02:56:08.049383: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:08.857679: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:08.871792: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:08.871906: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:08.872140: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:08.872787: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:08.872863: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:08.872906: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:09.165722: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:09.165896: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:09.165969: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:09.166029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:11.148121: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:11.148609: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:11.148645: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n"
          ]
        }
      ],
      "source": [
        "# !python /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py -s /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_images/3.jpg -t /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_images/4.jpg"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Defaulting to user installation because normal site-packages is not writeable\n",
            "Requirement already satisfied: tensorflow==2.8 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (2.8.0)\n",
            "Requirement already satisfied: h5py>=2.9.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (3.7.0)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (0.27.0)\n",
            "Requirement already satisfied: absl-py>=0.4.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (1.3.0)\n",
            "Requirement already satisfied: tf-estimator-nightly==2.8.0.dev2021122109 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (2.8.0.dev2021122109)\n",
            "Requirement already satisfied: gast>=0.2.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (0.4.0)\n",
            "Requirement already satisfied: numpy>=1.20 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (1.23.4)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (4.4.0)\n",
            "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow==2.8) (59.6.0)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (1.14.1)\n",
            "Requirement already satisfied: libclang>=9.0.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (14.0.6)\n",
            "Requirement already satisfied: protobuf>=3.9.2 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (3.20.3)\n",
            "Requirement already satisfied: keras<2.9,>=2.8.0rc0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (2.8.0)\n",
            "Requirement already satisfied: keras-preprocessing>=1.1.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (1.1.2)\n",
            "Requirement already satisfied: flatbuffers>=1.12 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (22.10.26)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (1.50.0)\n",
            "Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow==2.8) (1.16.0)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (0.2.0)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (2.1.0)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (3.3.0)\n",
            "Requirement already satisfied: tensorboard<2.9,>=2.8 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (2.8.0)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorflow==2.8) (1.6.3)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow==2.8) (0.37.1)\n",
            "Requirement already satisfied: google-auth<3,>=1.6.3 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8) (2.14.1)\n",
            "Requirement already satisfied: requests<3,>=2.21.0 in /usr/lib/python3/dist-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8) (2.25.1)\n",
            "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8) (1.8.1)\n",
            "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8) (0.4.6)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8) (3.4.1)\n",
            "Requirement already satisfied: werkzeug>=0.11.15 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8) (2.2.2)\n",
            "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from tensorboard<2.9,>=2.8->tensorflow==2.8) (0.6.1)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8) (0.2.8)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8) (4.9)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8) (5.2.0)\n",
            "Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow==2.8) (1.3.1)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from werkzeug>=0.11.15->tensorboard<2.9,>=2.8->tensorflow==2.8) (2.1.1)\n",
            "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/hpc-lavasa/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow==2.8) (0.4.8)\n",
            "Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow==2.8) (3.2.0)\n",
            "\u001b[1;31mE: \u001b[0mCould not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\u001b[0m\n",
            "\u001b[1;31mE: \u001b[0mUnable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\u001b[0m\n"
          ]
        }
      ],
      "source": [
        "# ! pip install tensorflow==2.8\n",
        "# ! apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "id": "3YFOggSEoqKP"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "video_name morphed_0_1.mp4\n",
            "STARTED\n"
          ]
        },
        {
          "ename": "NameError",
          "evalue": "name 'python_code_loc1' is not defined",
          "output_type": "error",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
            "Cell \u001b[0;32mIn [4], line 11\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mvideo_name \u001b[39m\u001b[39m\"\u001b[39m \u001b[39m+\u001b[39m video_name)\n\u001b[1;32m      9\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mSTARTED\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m---> 11\u001b[0m statement \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39mpython \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m -s \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m{}\u001b[39;00m\u001b[39m -t \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m{}\u001b[39;00m\u001b[39m --output \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m{}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39mformat(python_code_loc1, image_loc1, img_1_name, image_loc1, img_2_name, output_loc1, video_name)\n\u001b[1;32m     12\u001b[0m os\u001b[39m.\u001b[39msystem(statement)\n\u001b[1;32m     14\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mFINISHED\u001b[39m\u001b[39m\"\u001b[39m)\n",
            "\u001b[0;31mNameError\u001b[0m: name 'python_code_loc1' is not defined"
          ]
        }
      ],
      "source": [
        "# for img_1 in [0, 1, 2, 3, 4, 5]:\n",
        "#   for img_2 in [0, 1, 2, 3, 4, 5]:\n",
        "#     if img_1 < img_2:\n",
        "#       img_1_name = '{}.jpg'.format(img_1)\n",
        "#       img_2_name = '{}.jpg'.format(img_2)\n",
        "#       video_name = 'morphed_{}_{}.mp4'.format(img_1, img_2)\n",
        "\n",
        "#       print(\"video_name \" + video_name)\n",
        "#       print(\"STARTED\")\n",
        "\n",
        "#       statement = 'python {} -s {}{} -t {}{} --output {}{}'.format(python_code_loc1, image_loc1, img_1_name, image_loc1, img_2_name, output_loc1, video_name)\n",
        "#       os.system(statement)\n",
        "\n",
        "#       print(\"FINISHED\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "2022-11-27 02:56:32.827371: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:33.701819: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:33.716335: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:33.716481: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:33.716737: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:33.718086: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:33.718173: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:33.718219: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:34.027834: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:34.027977: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:34.028037: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:34.028112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:35.968633: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:35.968712: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:35.968742: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:01<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:56:36.854950: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:37.685510: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.699265: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.699379: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.699622: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:37.700511: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.700594: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.700638: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.994278: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.994440: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.994494: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:37.994557: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:40.080219: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:40.080803: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:40.080847: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:56:41.027692: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:41.893596: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:41.907797: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:41.907949: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:41.908197: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:41.908703: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:41.908783: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:41.908828: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:42.203239: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:42.203364: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:42.203420: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:42.203476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:44.238319: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:44.238613: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:44.238646: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:56:45.081413: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:45.873590: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:45.887616: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:45.887730: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:45.887968: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:45.888489: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:45.888560: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:45.888605: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:46.173534: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:46.173655: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:46.173705: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:46.173758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:48.144643: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:48.145130: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:48.145195: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:01<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:56:48.958918: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:49.721643: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:49.735493: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:49.735636: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:49.735878: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:49.736760: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:49.736873: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:49.736918: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:50.018431: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:50.018575: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:50.018654: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:50.018710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:51.957502: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:51.957619: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:51.957654: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:01<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:56:52.783546: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:53.545597: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.558984: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.559101: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.559323: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:53.560306: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.560394: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.560439: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.840434: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.840570: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.840622: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:53.840675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:55.820789: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:55.821300: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:55.821360: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:56:56.661896: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:56:57.453681: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.467174: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.467279: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.467520: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:56:57.469200: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.469339: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.469435: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.743661: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.743769: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.743817: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:56:57.743869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:56:59.752516: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:56:59.752820: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:56:59.752855: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "^C\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:57:00.418365: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:57:01.198960: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.213682: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.213842: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.214095: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:57:01.215056: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.215182: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.215245: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.497010: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.497130: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.497183: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:01.497241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:57:03.489720: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:57:03.490192: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:57:03.490227: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:57:04.375973: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:57:05.189661: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.203838: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.203961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.204203: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:57:05.204770: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.204852: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.204895: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.494460: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.494579: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.494631: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:05.494682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:57:07.498633: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:57:07.499120: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:57:07.499172: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:02<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n",
            "mv: cannot stat '/content/DiffMorph/morph/morph.mp4': No such file or directory\n",
            "2022-11-27 02:57:08.324374: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2022-11-27 02:57:09.121742: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.136045: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.136160: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.136393: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2022-11-27 02:57:09.137368: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.137450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.137493: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.428244: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.428364: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.428414: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2022-11-27 02:57:09.428465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 229 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:00<?, ?it/s]2022-11-27 02:57:11.373919: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED\n",
            "2022-11-27 02:57:11.374289: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 520.61.5\n",
            "2022-11-27 02:57:11.374348: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.\n",
            "Epoch 1, Loss: 0.0:   0%|                              | 0/1000 [00:01<?, ?it/s]\n",
            "Traceback (most recent call last):\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "    produce_warp_maps(origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "    train_step(maps, origins, targets)\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
            "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
            "tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n",
            "\n",
            "Detected at node 'my_model/conv2d/Conv2D' defined at (most recent call last):\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 240, in <module>\n",
            "      produce_warp_maps(origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 102, in produce_warp_maps\n",
            "      train_step(maps, origins, targets)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 71, in train_step\n",
            "      preds = model(maps)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/training.py\", line 490, in __call__\n",
            "      return super().__call__(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py\", line 53, in call\n",
            "      x = self.conv1(x)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1014, in __call__\n",
            "      outputs = call_fn(inputs, *args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n",
            "      return fn(*args, **kwargs)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n",
            "      outputs = self.convolution_op(inputs, self.kernel)\n",
            "    File \"/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/JAGGU/lib/python3.9/site-packages/keras/layers/convolutional/base_conv.py\", line 225, in convolution_op\n",
            "      return tf.nn.convolution(\n",
            "Node: 'my_model/conv2d/Conv2D'\n",
            "DNN library is not found.\n",
            "\t [[{{node my_model/conv2d/Conv2D}}]] [Op:__inference_train_step_2661]\n"
          ]
        }
      ],
      "source": [
        "image_list = [file for file in os.listdir('/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_Images_2') if not file.startswith('.')]\n",
        "image_list.sort()\n",
        "epochs = 1000 #@param {type:\"number\"}\n",
        "warp_scale = 0.05 #@param {type:\"number\"}\n",
        "mult_scale = 0.4 #@param {type:\"number\"}\n",
        "add_scale = 0.4 #@param {type:\"number\"}\n",
        "add_first = False #@param {type:\"boolean\"}\n",
        "filenames = []\n",
        "for i in range(len(image_list) - 1):\n",
        "    start = f'/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_Images_2/{image_list[i]}'\n",
        "    end = f'/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/Renamed_Images_2/{image_list[i+1]}'\n",
        "    if add_first:\n",
        "        !python m/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py -s $start -t $end -e $epochs -a $add_scale -m $mult_scale -w $warp_scale --add_first\n",
        "    else:\n",
        "        !python /home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/DiffMorph-master/morph.py -s $start -t $end -e $epochs -a $add_scale -m $mult_scale -w $warp_scale\n",
        "    filename = f'/home/hpc-lavasa/Desktop/Avastha_Research-20221126T174731Z-001/Avastha_Research/output_videos2/morph{i:03d}.mp4'\n",
        "    filenames.append(filename)\n",
        "    !mv /content/DiffMorph/morph/morph.mp4 $filename"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3.9.12 ('JAGGU': venv)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.12"
    },
    "vscode": {
      "interpreter": {
        "hash": "0ddea20a7446bd5bbe36b039ce908bc6cdab5e5e109a4d15eb45b81c1583fe78"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
